# fly.toml app configuration file generated for noona-shopping-mall-yym on 2024-10-25T20:50:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noona-shopping-mall-yym'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4400
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
